package com.amazonaws.samples;

import java.util.HashMap;
import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerated;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="ConfigurationTable3")
public class MapClass {

	
	
	private String domain;
	private String realm;
	private String cfgKey;
	private String stringValue;
	private Integer integerValue;
	private MapValue mapValue;
	
	
	
	
	
 @DynamoDBHashKey(attributeName="DomainName")
 	public String getDomainName() { return domain; }
 	public void setDomainName(String domain) {this.domain = domain; }
 	
 	
 	
 @DynamoDBRangeKey(attributeName = "Realm")
	public String getRealm() {return realm;}
 	public void setRealm(String realm) {this.realm = realm; }
 
 
 @DynamoDBAttribute(attributeName="CfgKey")
 	public String getCfgKey() {return cfgKey; }
	public void setCfgKey(String cfgKey) { this.cfgKey= cfgKey; }
 	
 
 @DynamoDBAttribute(attributeName="StringValue")
	public String getStringValue() {return stringValue; }
  	public void setStringValue(String stringValue) { this.stringValue= stringValue; }
		
		
	 	
		 
 @DynamoDBAttribute(attributeName="IntegerValue")
 	public Integer getIntegerValue() {return integerValue; }
	public void setIntegerValue(Integer integerValue) { this.integerValue= integerValue; }
				
				
	 	
		
 @DynamoDBAttribute(attributeName="MapValue")
	 public MapValue getMapValue() { return mapValue;}
	 public void setMapValue(MapValue mapValue) {this.mapValue = mapValue;}
	 	 // Additional properties go here.
	 	
	

// @DynamoDBAttribute(attributeName="ISBN")
// 	public String getISBN() { return ISBN; }
// 	public void setISBN(String ISBN) { this.ISBN = ISBN; }
// 	
// 	
// @DynamoDBAttribute(attributeName="Authors")
// public Set<String> getBookAuthors() { return bookAuthors; }
// public void setBookAuthors(Set<String> bookAuthors) { this.bookAuthors = bookAuthors; }


 	 
 	 @DynamoDBDocument
 	 public static class MapValue {
 		 
 		 private String credentials;
 		 private String url;
 		 private String reservationRequestsqueueURL;
 		 private String manualApprovalqueueURL;
 		 private String crawlCompletionResponsequeueURL;
 		 private String subscriptionsAllocationqueueURL;
 		 
 		
 		 @DynamoDBAttribute(attributeName = "Credentials")
 		 public String getCredentials() { return credentials; }
 		 public void setCredentials(String credentials) { this.credentials = credentials; }
 		 
 		 @DynamoDBAttribute(attributeName = "URL")
 		 public String getUrl() { return url; }
 		 public void setUrl(String url) { this.url = url; }
 		 
 		 @DynamoDBAttribute(attributeName = "ReservationRequestsqueueURL")
 		 public String getReservationRequestsqueueURL() { return reservationRequestsqueueURL; }
 		 public void setReservationRequestsqueueURL(String reservationRequestsqueueURL) { this.reservationRequestsqueueURL = reservationRequestsqueueURL; }
 		 
 		 @DynamoDBAttribute(attributeName = "ManualApprovalqueueURL")
 		 public String getManualApprovalqueueURL() { return manualApprovalqueueURL; }
 		 public void setManualApprovalqueueURL(String manualApprovalqueueURL) { this.manualApprovalqueueURL = manualApprovalqueueURL; }
 		 
 		 @DynamoDBAttribute(attributeName = "CrawlCompletionResponsequeueURL")
 		 public String getCrawlCompletionResponsequeueURL() { return crawlCompletionResponsequeueURL; }
 		 public void setCrawlCompletionResponsequeueURL(String crawlCompletionResponsequeueURL) { this.crawlCompletionResponsequeueURL = crawlCompletionResponsequeueURL; }
 		 
 		 @DynamoDBAttribute(attributeName = "SubscriptionsAllocationqueueURL")
 		 public String getSubscriptionsAllocationqueueURL() { return subscriptionsAllocationqueueURL; }
 		 public void setSubscriptionsAllocationqueueURL(String subscriptionsAllocationqueueURL) { this.subscriptionsAllocationqueueURL = subscriptionsAllocationqueueURL; }

 	 }

}



